version: '3'

services:
  main:
    container_name: {{cookiecutter.project_name}}_main
    build:
      context: .
      dockerfile: Dockerfile.main
    image: {{cookiecutter.project_name}}_main:latest
    volumes:
      - ".:/app"
  fastapi:
    container_name: {{cookiecutter.project_name}}_fastapi
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    image: {{cookiecutter.project_name}}_fastapi:latest
    volumes:
      - ".:/app"
    ports:
      - "8000:8000"
